CREATE DATABASE IF NOT EXISTS csua_intrams;
USE csua_intrams;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin') NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS colleges (
  id VARCHAR(100) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(100) NOT NULL DEFAULT '',
  photo_url TEXT NULL,
  events JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedule (
  id VARCHAR(36) PRIMARY KEY,
  sport VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  event VARCHAR(255) NULL,
  game INT NOT NULL,
  teams JSON NOT NULL,
  type ENUM('h2h', 'multi') NOT NULL,
  winner VARCHAR(255) NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NULL
);